.class public Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;
.super Ljava/lang/Object;
.source "OffscreenRenderer.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$1;,
        Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;
    }
.end annotation


# static fields
.field private static final EGL_ALPHA_SIZE_IDX:I = 0x7

.field private static final EGL_BLUE_SIZE_IDX:I = 0x5

.field private static final EGL_CONTEXT_CLIENT_VERSION:I = 0x3098

.field private static final EGL_DEPTH_SIZE_IDX:I = 0x9

.field private static final EGL_GREEN_SIZE_IDX:I = 0x3

.field private static final EGL_RED_SIZE_IDX:I = 0x1

.field private static final EGL_STENCIL_SIZE_IDX:I = 0xb

.field private static final NUM_OFFSCREEN_BUFFS:I = 0x2

.field private static final NUM_OFFSCREEN_TEXTURES:I = 0x3

.field private static OES_TEXTURE_IDX:I = 0x0

.field private static final TAG:Ljava/lang/String;

.field public static final UNIQUE_ID:Ljava/lang/String; = "Generated by Sony GAW:1.0"

.field static final mNumSignaturePxls:I

.field static final mSignatureData:[B

.field static final mSignatureLength:I


# instance fields
.field private isOESFBSupported:Z

.field private mClearingBits:I

.field private mConfigSpec:[I

.field private mCurrentFB:I

.field private mCurrentTexture:I

.field private mEgl:Ljavax/microedition/khronos/egl/EGL10;

.field private mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

.field private mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

.field private mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

.field private mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

.field private mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

.field private mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

.field private mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

.field private mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

.field private mFBO:[I

.field private mGlobalTransform:[F

.field private mHeight:I

.field private mNeedContextSwitch:Z

.field private mOESFBO:I

.field private mOffscreenTexture:[I

.field private mPBO:I

.field private mPBOSize:I

.field private mResBuffer:Ljava/nio/ByteBuffer;

.field private mScissorsEnabled:Z

.field private mSignaturePixels:[I

.field private mTempCanvas:Landroid/graphics/Canvas;

.field private mWidth:I


# direct methods
.method static constructor <clinit>()V
    .locals 2

    .prologue
    const-class v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;

    .line 53
    invoke-virtual {v0}, Ljava/lang/Class;->getName()Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->TAG:Ljava/lang/String;

    const/4 v0, 0x2

    .line 60
    sput v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->OES_TEXTURE_IDX:I

    const-string/jumbo v0, "Generated by Sony GAW:1.0"

    const-string/jumbo v1, "US-ASCII"

    .line 80
    invoke-static {v1}, Ljava/nio/charset/Charset;->forName(Ljava/lang/String;)Ljava/nio/charset/Charset;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/String;->getBytes(Ljava/nio/charset/Charset;)[B

    move-result-object v0

    sput-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    .line 81
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    array-length v0, v0

    sput v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    .line 82
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    mul-int/lit8 v0, v0, 0x2

    sput v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    return-void
.end method

.method public constructor <init>()V
    .locals 4

    .prologue
    const/4 v1, -0x1

    const/high16 v3, 0x3f800000    # 1.0f

    const/4 v2, 0x0

    .line 137
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 83
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    new-array v0, v0, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    const/4 v0, 0x3

    .line 85
    new-array v0, v0, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    const/4 v0, 0x2

    .line 87
    new-array v0, v0, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    .line 90
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    .line 91
    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    .line 93
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    .line 95
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentTexture:I

    .line 97
    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBO:I

    .line 99
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBOSize:I

    .line 105
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_DISPLAY:Ljavax/microedition/khronos/egl/EGLDisplay;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 107
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 109
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 111
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 113
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 115
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 117
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_DISPLAY:Ljavax/microedition/khronos/egl/EGLDisplay;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 119
    iput-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    .line 123
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    const/16 v0, 0x10

    .line 134
    new-array v0, v0, [F

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    .line 135
    iput-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    .line 138
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-static {v0, v2}, Landroid/opengl/Matrix;->setIdentityM([FI)V

    .line 139
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    const/high16 v1, -0x40800000    # -1.0f

    invoke-static {v0, v2, v3, v1, v3}, Landroid/opengl/Matrix;->scaleM([FIFFF)V

    .line 141
    new-instance v0, Landroid/graphics/Canvas;

    invoke-direct {v0}, Landroid/graphics/Canvas;-><init>()V

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mTempCanvas:Landroid/graphics/Canvas;

    .line 142
    return-void
.end method

.method private addSignatureInfo(Landroid/graphics/Bitmap;)V
    .locals 10

    .prologue
    const v9, -0x1010102

    const/4 v2, 0x0

    .line 585
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    mul-int/lit8 v0, v0, 0x8

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getByteCount()I

    move-result v1

    mul-int/lit8 v1, v1, 0x4

    if-lt v0, v1, :cond_0

    .line 624
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "Too large string for hiding"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 586
    :cond_0
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v1

    if-gt v0, v1, :cond_2

    sget v6, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    .line 589
    :goto_0
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v1

    div-int/2addr v0, v1

    .line 590
    sget v1, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    rem-int/2addr v1, v3

    if-nez v1, :cond_3

    .line 593
    :goto_1
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getHeight()I

    move-result v1

    if-gt v0, v1, :cond_4

    move v7, v0

    .line 599
    :goto_2
    mul-int v0, v6, v7

    .line 600
    sget v1, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    if-lt v1, v0, :cond_5

    .line 604
    :cond_1
    :goto_3
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    move-object v0, p1

    move v4, v2

    move v5, v2

    invoke-virtual/range {v0 .. v7}, Landroid/graphics/Bitmap;->getPixels([IIIIIII)V

    move v0, v2

    move v1, v2

    .line 606
    :goto_4
    sget v3, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    if-lt v0, v3, :cond_6

    .line 622
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    move-object v0, p1

    move v4, v2

    move v5, v2

    invoke-virtual/range {v0 .. v7}, Landroid/graphics/Bitmap;->setPixels([IIIIIII)V

    .line 626
    return-void

    .line 586
    :cond_2
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v6

    goto :goto_0

    .line 591
    :cond_3
    add-int/lit8 v0, v0, 0x1

    goto :goto_1

    .line 593
    :cond_4
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getHeight()I

    move-result v7

    goto :goto_2

    .line 600
    :cond_5
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    array-length v1, v1

    if-ge v1, v0, :cond_1

    .line 601
    new-array v0, v0, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    goto :goto_3

    .line 607
    :cond_6
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v4, v1, 0x1

    aget v5, v3, v4

    and-int/2addr v5, v9

    aput v5, v3, v4

    .line 608
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v4, v1, 0x1

    aget v5, v3, v4

    sget-object v8, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v8, v8, v0

    shr-int/lit8 v8, v8, 0x0

    and-int/lit8 v8, v8, 0x1

    shl-int/lit8 v8, v8, 0x0

    or-int/2addr v5, v8

    aput v5, v3, v4

    .line 609
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v4, v1, 0x1

    aget v5, v3, v4

    sget-object v8, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v8, v8, v0

    shr-int/lit8 v8, v8, 0x1

    and-int/lit8 v8, v8, 0x1

    shl-int/lit8 v8, v8, 0x8

    or-int/2addr v5, v8

    aput v5, v3, v4

    .line 610
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v4, v1, 0x1

    aget v5, v3, v4

    sget-object v8, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v8, v8, v0

    shr-int/lit8 v8, v8, 0x2

    and-int/lit8 v8, v8, 0x1

    shl-int/lit8 v8, v8, 0x10

    or-int/2addr v5, v8

    aput v5, v3, v4

    .line 611
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v4, v1, 0x1

    aget v5, v3, v4

    sget-object v8, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v8, v8, v0

    shr-int/lit8 v8, v8, 0x3

    and-int/lit8 v8, v8, 0x1

    shl-int/lit8 v8, v8, 0x18

    or-int/2addr v5, v8

    aput v5, v3, v4

    .line 613
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v4, v3, v1

    and-int/2addr v4, v9

    aput v4, v3, v1

    .line 614
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v4, v3, v1

    sget-object v5, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v5, v5, v0

    shr-int/lit8 v5, v5, 0x4

    and-int/lit8 v5, v5, 0x1

    shl-int/lit8 v5, v5, 0x0

    or-int/2addr v4, v5

    aput v4, v3, v1

    .line 615
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v4, v3, v1

    sget-object v5, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v5, v5, v0

    shr-int/lit8 v5, v5, 0x5

    and-int/lit8 v5, v5, 0x1

    shl-int/lit8 v5, v5, 0x8

    or-int/2addr v4, v5

    aput v4, v3, v1

    .line 616
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v4, v3, v1

    sget-object v5, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v5, v5, v0

    shr-int/lit8 v5, v5, 0x6

    and-int/lit8 v5, v5, 0x1

    shl-int/lit8 v5, v5, 0x10

    or-int/2addr v4, v5

    aput v4, v3, v1

    .line 617
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v4, v3, v1

    sget-object v5, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v5, v5, v0

    shr-int/lit8 v5, v5, 0x7

    and-int/lit8 v5, v5, 0x1

    shl-int/lit8 v5, v5, 0x18

    or-int/2addr v4, v5

    aput v4, v3, v1

    .line 619
    add-int/lit8 v1, v1, 0x2

    .line 606
    add-int/lit8 v0, v0, 0x1

    goto/16 :goto_4
.end method

.method private chooseConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;)Ljavax/microedition/khronos/egl/EGLConfig;
    .locals 6

    .prologue
    const/4 v3, 0x0

    const/4 v4, 0x0

    const/4 v0, 0x1

    .line 307
    new-array v5, v0, [I

    .line 309
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    move-object v0, p1

    move-object v1, p2

    invoke-interface/range {v0 .. v5}, Ljavax/microedition/khronos/egl/EGL10;->eglChooseConfig(Ljavax/microedition/khronos/egl/EGLDisplay;[I[Ljavax/microedition/khronos/egl/EGLConfig;I[I)Z

    move-result v0

    if-eqz v0, :cond_0

    .line 313
    aget v4, v5, v4

    .line 314
    if-lez v4, :cond_1

    .line 319
    new-array v3, v4, [Ljavax/microedition/khronos/egl/EGLConfig;

    .line 320
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    move-object v0, p1

    move-object v1, p2

    invoke-interface/range {v0 .. v5}, Ljavax/microedition/khronos/egl/EGL10;->eglChooseConfig(Ljavax/microedition/khronos/egl/EGLDisplay;[I[Ljavax/microedition/khronos/egl/EGLConfig;I[I)Z

    move-result v0

    if-eqz v0, :cond_2

    .line 324
    invoke-direct {p0, p1, p2, v3}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;[Ljavax/microedition/khronos/egl/EGLConfig;)Ljavax/microedition/khronos/egl/EGLConfig;

    move-result-object v0

    .line 325
    if-eqz v0, :cond_3

    .line 328
    return-object v0

    .line 310
    :cond_0
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "eglChooseConfig failed"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 315
    :cond_1
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "No configs match configSpec"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 321
    :cond_2
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "eglChooseConfig#2 failed"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 326
    :cond_3
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "No config chosen"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method private createOffscreenBuffs()V
    .locals 14

    .prologue
    const/4 v13, 0x2

    const/4 v12, 0x3

    const v11, 0x8d40

    const/16 v0, 0xde1

    const/4 v1, 0x0

    .line 363
    new-array v10, v12, [I

    .line 366
    invoke-static {v12, v10, v1}, Landroid/opengl/GLES20;->glGenTextures(I[II)V

    .line 367
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const v2, 0x84c0

    .line 368
    invoke-static {v2}, Landroid/opengl/GLES20;->glActiveTexture(I)V

    .line 369
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    move v9, v1

    .line 371
    :goto_0
    if-lt v9, v12, :cond_0

    .line 391
    invoke-static {v13, v10, v1}, Landroid/opengl/GLES20;->glGenFramebuffers(I[II)V

    .line 392
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    move v2, v1

    .line 394
    :goto_1
    if-lt v2, v13, :cond_1

    .line 406
    iget-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    if-nez v2, :cond_2

    .line 422
    :goto_2
    invoke-static {v11, v1}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 423
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 424
    return-void

    .line 372
    :cond_0
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    aget v3, v10, v9

    aput v3, v2, v9

    .line 374
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    aget v2, v2, v9

    invoke-static {v0, v2}, Landroid/opengl/GLES20;->glBindTexture(II)V

    .line 375
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x1908

    .line 376
    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    const/16 v6, 0x1908

    const/16 v7, 0x1401

    const/4 v8, 0x0

    move v5, v1

    invoke-static/range {v0 .. v8}, Landroid/opengl/GLES20;->glTexImage2D(IIIIIIIILjava/nio/Buffer;)V

    .line 378
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2801

    const/16 v3, 0x2600

    .line 379
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 381
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2800

    const/16 v3, 0x2600

    .line 382
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 384
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2802

    const/16 v3, 0x2901

    .line 385
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 386
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2803

    const/16 v3, 0x2901

    .line 387
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 388
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 371
    add-int/lit8 v2, v9, 0x1

    move v9, v2

    goto :goto_0

    .line 395
    :cond_1
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    aget v4, v10, v2

    aput v4, v3, v2

    .line 397
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    aget v3, v3, v2

    invoke-static {v11, v3}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 398
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const v3, 0x8ce0

    .line 399
    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    aget v4, v4, v2

    invoke-static {v11, v3, v0, v4, v1}, Landroid/opengl/GLES20;->glFramebufferTexture2D(IIIII)V

    .line 401
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 402
    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    invoke-static {v1, v1, v3, v4}, Landroid/opengl/GLES20;->glViewport(IIII)V

    .line 403
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 394
    add-int/lit8 v2, v2, 0x1

    goto/16 :goto_1

    :cond_2
    const/4 v2, 0x1

    .line 408
    invoke-static {v2, v10, v1}, Landroid/opengl/GLES11Ext;->glGenFramebuffersOES(I[II)V

    .line 409
    aget v2, v10, v1

    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    .line 411
    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    invoke-static {v11, v2}, Landroid/opengl/GLES11Ext;->glBindFramebufferOES(II)V

    .line 412
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const v2, 0x8ce0

    .line 413
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    sget v4, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->OES_TEXTURE_IDX:I

    aget v3, v3, v4

    invoke-static {v11, v2, v0, v3, v1}, Landroid/opengl/GLES11Ext;->glFramebufferTexture2DOES(IIIII)V

    .line 418
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 419
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    invoke-static {v1, v1, v0, v2}, Landroid/opengl/GLES20;->glViewport(IIII)V

    .line 420
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    goto/16 :goto_2
.end method

.method private findConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;[Ljavax/microedition/khronos/egl/EGLConfig;)Ljavax/microedition/khronos/egl/EGLConfig;
    .locals 11

    .prologue
    const/4 v5, 0x0

    .line 332
    array-length v7, p3

    move v6, v5

    :goto_0
    if-lt v6, v7, :cond_0

    const/4 v0, 0x0

    .line 347
    return-object v0

    .line 332
    :cond_0
    aget-object v3, p3, v6

    const/16 v4, 0x3025

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    .line 333
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v8

    const/16 v4, 0x3026

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    .line 334
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v0

    .line 335
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/16 v2, 0x9

    aget v1, v1, v2

    if-ge v8, v1, :cond_2

    .line 332
    :cond_1
    add-int/lit8 v0, v6, 0x1

    move v6, v0

    goto :goto_0

    .line 335
    :cond_2
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/16 v2, 0xb

    aget v1, v1, v2

    if-lt v0, v1, :cond_1

    const/16 v4, 0x3024

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    .line 336
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v8

    const/16 v4, 0x3023

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    .line 337
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v9

    const/16 v4, 0x3022

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    .line 338
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v10

    const/16 v4, 0x3021

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    .line 339
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v0

    .line 340
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v2, 0x1

    aget v1, v1, v2

    if-ne v8, v1, :cond_1

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v2, 0x3

    aget v1, v1, v2

    if-ne v9, v1, :cond_1

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v2, 0x5

    aget v1, v1, v2

    if-ne v10, v1, :cond_1

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v2, 0x7

    aget v1, v1, v2

    if-ne v0, v1, :cond_1

    .line 343
    return-object v3
.end method

.method private findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I
    .locals 3

    .prologue
    const/4 v2, 0x0

    const/4 v0, 0x1

    .line 353
    new-array v0, v0, [I

    .line 354
    invoke-interface {p1, p2, p3, p4, v0}, Ljavax/microedition/khronos/egl/EGL10;->eglGetConfigAttrib(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;I[I)Z

    move-result v1

    if-nez v1, :cond_0

    .line 357
    return p5

    .line 355
    :cond_0
    aget v0, v0, v2

    return v0
.end method


# virtual methods
.method public checkSignatureInfo(Landroid/graphics/Bitmap;)Z
    .locals 10

    .prologue
    const/4 v2, 0x0

    .line 630
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getHeight()I

    move-result v0

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getRowBytes()I

    move-result v1

    mul-int/2addr v0, v1

    .line 631
    sget v1, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    mul-int/lit8 v1, v1, 0x8

    if-lt v1, v0, :cond_0

    .line 664
    :goto_0
    return v2

    .line 632
    :cond_0
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    new-array v8, v0, [B

    .line 633
    sget v9, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    .line 635
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    new-array v1, v0, [I

    .line 637
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    if-gt v0, v3, :cond_1

    sget v6, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    .line 640
    :goto_1
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    div-int v7, v0, v3

    .line 641
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    rem-int/2addr v0, v3

    if-nez v0, :cond_2

    .line 645
    :goto_2
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    move-object v0, p1

    move v4, v2

    move v5, v2

    invoke-virtual/range {v0 .. v7}, Landroid/graphics/Bitmap;->getPixels([IIIIIII)V

    move v0, v2

    .line 648
    :goto_3
    if-lt v2, v9, :cond_3

    .line 661
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    invoke-static {v8, v0}, Ljava/util/Arrays;->equals([B[B)Z

    move-result v2

    goto :goto_0

    .line 637
    :cond_1
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v6

    goto :goto_1

    .line 642
    :cond_2
    add-int/lit8 v7, v7, 0x1

    goto :goto_2

    .line 649
    :cond_3
    aget-byte v3, v8, v2

    aget v4, v1, v0

    shr-int/lit8 v4, v4, 0x18

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x7

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 650
    aget-byte v3, v8, v2

    aget v4, v1, v0

    shr-int/lit8 v4, v4, 0x10

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x6

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 651
    aget-byte v3, v8, v2

    aget v4, v1, v0

    shr-int/lit8 v4, v4, 0x8

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x5

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 652
    aget-byte v3, v8, v2

    aget v4, v1, v0

    shr-int/lit8 v4, v4, 0x0

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x4

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 654
    aget-byte v3, v8, v2

    add-int/lit8 v4, v0, 0x1

    aget v4, v1, v4

    shr-int/lit8 v4, v4, 0x18

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x3

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 655
    aget-byte v3, v8, v2

    add-int/lit8 v4, v0, 0x1

    aget v4, v1, v4

    shr-int/lit8 v4, v4, 0x10

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x2

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 656
    aget-byte v3, v8, v2

    add-int/lit8 v4, v0, 0x1

    aget v4, v1, v4

    shr-int/lit8 v4, v4, 0x8

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x1

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 657
    aget-byte v3, v8, v2

    add-int/lit8 v4, v0, 0x1

    aget v4, v1, v4

    shr-int/lit8 v4, v4, 0x0

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x0

    int-to-byte v4, v4

    or-int/2addr v3, v4

    int-to-byte v3, v3

    int-to-byte v3, v3

    aput-byte v3, v8, v2

    .line 658
    add-int/lit8 v0, v0, 0x2

    .line 648
    add-int/lit8 v2, v2, 0x1

    goto/16 :goto_3
.end method

.method public getCurrentTexture()I
    .locals 1

    .prologue
    .line 541
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentTexture:I

    return v0
.end method

.method public init(IIIIIIII)V
    .locals 5

    .prologue
    .line 149
    iput p7, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    .line 150
    iput p8, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    .line 155
    invoke-static {}, Ljavax/microedition/khronos/egl/EGLContext;->getEGL()Ljavax/microedition/khronos/egl/EGL;

    move-result-object v0

    check-cast v0, Ljavax/microedition/khronos/egl/EGL10;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    .line 160
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    sget-object v1, Ljavax/microedition/khronos/egl/EGL10;->EGL_DEFAULT_DISPLAY:Ljava/lang/Object;

    invoke-interface {v0, v1}, Ljavax/microedition/khronos/egl/EGL10;->eglGetDisplay(Ljava/lang/Object;)Ljavax/microedition/khronos/egl/EGLDisplay;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 161
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    sget-object v1, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_DISPLAY:Ljavax/microedition/khronos/egl/EGLDisplay;

    if-eq v0, v1, :cond_1

    const/4 v0, 0x2

    .line 168
    new-array v0, v0, [I

    .line 169
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-interface {v1, v2, v0}, Ljavax/microedition/khronos/egl/EGL10;->eglInitialize(Ljavax/microedition/khronos/egl/EGLDisplay;[I)Z

    move-result v0

    if-eqz v0, :cond_2

    const/16 v0, 0x15

    .line 176
    new-array v0, v0, [I

    const/4 v1, 0x0

    const/16 v2, 0x3024

    aput v2, v0, v1

    const/4 v1, 0x1

    aput p1, v0, v1

    const/4 v1, 0x2

    const/16 v2, 0x3023

    aput v2, v0, v1

    const/4 v1, 0x3

    aput p2, v0, v1

    const/4 v1, 0x4

    const/16 v2, 0x3022

    aput v2, v0, v1

    const/4 v1, 0x5

    aput p3, v0, v1

    const/4 v1, 0x6

    const/16 v2, 0x3021

    aput v2, v0, v1

    const/4 v1, 0x7

    aput p4, v0, v1

    const/16 v1, 0x8

    const/16 v2, 0x3025

    aput v2, v0, v1

    const/16 v1, 0x9

    aput p5, v0, v1

    const/16 v1, 0xa

    const/16 v2, 0x3026

    aput v2, v0, v1

    const/16 v1, 0xb

    aput p6, v0, v1

    const/16 v1, 0xc

    const/16 v2, 0x3033

    aput v2, v0, v1

    const/16 v1, 0xd

    const/4 v2, 0x1

    aput v2, v0, v1

    const/16 v1, 0xe

    const/16 v2, 0x3042

    aput v2, v0, v1

    const/16 v1, 0xf

    const/4 v2, 0x4

    aput v2, v0, v1

    const/16 v1, 0x10

    const/16 v2, 0x3040

    aput v2, v0, v1

    const/16 v1, 0x11

    const/4 v2, 0x4

    aput v2, v0, v1

    const/16 v1, 0x12

    const/16 v2, 0x303a

    aput v2, v0, v1

    const/16 v1, 0x13

    const/4 v2, 0x1

    aput v2, v0, v1

    const/16 v1, 0x14

    const/16 v2, 0x3038

    aput v2, v0, v1

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/16 v0, 0x4000

    .line 193
    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    .line 194
    if-nez p5, :cond_3

    .line 198
    :goto_0
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-direct {p0, v0, v1}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->chooseConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;)Ljavax/microedition/khronos/egl/EGLConfig;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

    const/4 v0, 0x3

    .line 205
    new-array v0, v0, [I

    const/4 v1, 0x0

    const/16 v2, 0x3098

    aput v2, v0, v1

    const/4 v1, 0x1

    const/4 v2, 0x3

    aput v2, v0, v1

    const/4 v1, 0x2

    const/16 v2, 0x3038

    aput v2, v0, v1

    .line 208
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

    sget-object v4, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v1, v2, v3, v4, v0}, Ljavax/microedition/khronos/egl/EGL10;->eglCreateContext(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;Ljavax/microedition/khronos/egl/EGLContext;[I)Ljavax/microedition/khronos/egl/EGLContext;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 210
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    if-nez v0, :cond_4

    :cond_0
    const/4 v0, 0x0

    .line 211
    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 212
    new-instance v0, Ljava/lang/RuntimeException;

    const-string/jumbo v1, "eglCreateContext failed"

    invoke-direct {v0, v1}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 162
    :cond_1
    new-instance v0, Ljava/lang/RuntimeException;

    const-string/jumbo v1, "eglGetDisplay failed"

    invoke-direct {v0, v1}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 170
    :cond_2
    new-instance v0, Ljava/lang/RuntimeException;

    const-string/jumbo v1, "eglInitialize failed"

    invoke-direct {v0, v1}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 195
    :cond_3
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    or-int/lit16 v0, v0, 0x100

    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    goto :goto_0

    .line 210
    :cond_4
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    sget-object v1, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    if-eq v0, v1, :cond_0

    .line 217
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    mul-int/2addr v0, v1

    mul-int/lit8 v0, v0, 0x4

    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBOSize:I

    .line 218
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBOSize:I

    invoke-static {v0}, Ljava/nio/ByteBuffer;->allocateDirect(I)Ljava/nio/ByteBuffer;

    move-result-object v0

    invoke-static {}, Ljava/nio/ByteOrder;->nativeOrder()Ljava/nio/ByteOrder;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/nio/ByteBuffer;->order(Ljava/nio/ByteOrder;)Ljava/nio/ByteBuffer;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    const/16 v0, 0x9

    .line 223
    new-array v0, v0, [I

    const/4 v1, 0x0

    const/16 v2, 0x3057

    aput v2, v0, v1

    const/4 v1, 0x1

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    aput v2, v0, v1

    const/4 v1, 0x2

    const/16 v2, 0x3056

    aput v2, v0, v1

    const/4 v1, 0x3

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    aput v2, v0, v1

    const/4 v1, 0x4

    const/16 v2, 0x3080

    aput v2, v0, v1

    const/4 v1, 0x5

    const/16 v2, 0x305e

    aput v2, v0, v1

    const/4 v1, 0x6

    const/16 v2, 0x3081

    aput v2, v0, v1

    const/4 v1, 0x7

    const/16 v2, 0x305f

    aput v2, v0, v1

    const/16 v1, 0x8

    const/16 v2, 0x3038

    aput v2, v0, v1

    .line 228
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

    invoke-interface {v1, v2, v3, v0}, Ljavax/microedition/khronos/egl/EGL10;->eglCreatePbufferSurface(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;[I)Ljavax/microedition/khronos/egl/EGLSurface;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 229
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    if-nez v0, :cond_6

    .line 230
    :cond_5
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v0}, Ljavax/microedition/khronos/egl/EGL10;->eglGetError()I

    move-result v0

    const/16 v1, 0x300b

    .line 231
    if-eq v0, v1, :cond_7

    .line 236
    :goto_1
    invoke-virtual {p0}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->makeCurrentIfNeeded()V

    const/high16 v0, 0x3e800000    # 0.25f

    const/high16 v1, 0x3e800000    # 0.25f

    const/high16 v2, 0x3e800000    # 0.25f

    const/high16 v3, 0x3f800000    # 1.0f

    .line 239
    invoke-static {v0, v1, v2, v3}, Landroid/opengl/GLES20;->glClearColor(FFFF)V

    .line 241
    invoke-direct {p0}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->createOffscreenBuffs()V

    .line 242
    return-void

    .line 229
    :cond_6
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    sget-object v1, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    if-eq v0, v1, :cond_5

    goto :goto_1

    .line 232
    :cond_7
    new-instance v0, Ljava/lang/RuntimeException;

    const-string/jumbo v1, "eglCreatePbufferSurface has failed"

    invoke-direct {v0, v1}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method public makeCurrentIfNeeded()V
    .locals 5

    .prologue
    .line 275
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v0}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentContext()Ljavax/microedition/khronos/egl/EGLContext;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 276
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    const/16 v1, 0x3059

    invoke-interface {v0, v1}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentSurface(I)Ljavax/microedition/khronos/egl/EGLSurface;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 277
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    const/16 v1, 0x305a

    invoke-interface {v0, v1}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentSurface(I)Ljavax/microedition/khronos/egl/EGLSurface;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 278
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v0}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentDisplay()Ljavax/microedition/khronos/egl/EGLDisplay;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 280
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    if-eq v0, v1, :cond_1

    .line 284
    :cond_0
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v0, v1, v2, v3, v4}, Ljavax/microedition/khronos/egl/EGL10;->eglMakeCurrent(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLContext;)Z

    move-result v0

    if-nez v0, :cond_2

    .line 287
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->TAG:Ljava/lang/String;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string/jumbo v2, "Can\'t perform context switch, err: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v2}, Ljavax/microedition/khronos/egl/EGL10;->eglGetError()I

    move-result v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Landroid/util/Log;->e(Ljava/lang/String;Ljava/lang/String;)I

    .line 290
    :goto_0
    return-void

    .line 280
    :cond_1
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    if-ne v0, v1, :cond_0

    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    if-ne v0, v1, :cond_0

    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    if-ne v0, v1, :cond_0

    goto :goto_0

    .line 285
    :cond_2
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    goto :goto_0
.end method

.method public release()V
    .locals 5

    .prologue
    const/4 v4, 0x2

    const/4 v3, 0x3

    const/4 v2, 0x0

    .line 248
    new-array v0, v3, [I

    .line 253
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    invoke-static {v1, v2, v0, v2, v4}, Ljava/lang/System;->arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V

    .line 254
    invoke-static {v4, v0, v2}, Landroid/opengl/GLES20;->glDeleteFramebuffers(I[II)V

    .line 255
    iget-boolean v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    if-nez v1, :cond_0

    .line 260
    :goto_0
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    invoke-static {v1, v2, v0, v2, v3}, Ljava/lang/System;->arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V

    .line 261
    invoke-static {v3, v0, v2}, Landroid/opengl/GLES20;->glDeleteTextures(I[II)V

    .line 262
    invoke-virtual {p0}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->restoreContextIfNeeded()V

    .line 265
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    invoke-interface {v0, v1, v2}, Ljavax/microedition/khronos/egl/EGL10;->eglDestroySurface(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLSurface;)Z

    .line 267
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v0, v1, v2}, Ljavax/microedition/khronos/egl/EGL10;->eglDestroyContext(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLContext;)Z

    .line 269
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-interface {v0, v1}, Ljavax/microedition/khronos/egl/EGL10;->eglTerminate(Ljavax/microedition/khronos/egl/EGLDisplay;)Z

    .line 270
    return-void

    .line 256
    :cond_0
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    aput v1, v0, v2

    const/4 v1, 0x1

    .line 257
    invoke-static {v1, v0, v2}, Landroid/opengl/GLES11Ext;->glDeleteFramebuffersOES(I[II)V

    goto :goto_0
.end method

.method public render(Landroid/graphics/Bitmap;Ljava/util/ArrayList;)V
    .locals 7
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Landroid/graphics/Bitmap;",
            "Ljava/util/ArrayList",
            "<",
            "Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;",
            ">;)V"
        }
    .end annotation

    .prologue
    const v6, 0x8d40

    const/4 v0, 0x0

    .line 428
    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    .line 430
    invoke-virtual {p2}, Ljava/util/ArrayList;->size()I

    move-result v3

    .line 431
    invoke-virtual {p2}, Ljava/util/ArrayList;->listIterator()Ljava/util/ListIterator;

    move-result-object v4

    .line 433
    invoke-virtual {p0}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->resetGlobalTransform()V

    move v2, v0

    .line 435
    :goto_0
    add-int/lit8 v1, v3, -0x1

    if-lt v2, v1, :cond_1

    .line 451
    invoke-static {v6, v0}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 452
    invoke-interface {v4}, Ljava/util/ListIterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-interface {v1, v2}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->draw(Ljava/lang/Object;)V

    .line 454
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {v1, v0}, Ljava/nio/ByteBuffer;->position(I)Ljava/nio/Buffer;

    .line 455
    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    const/16 v4, 0x1908

    const/16 v5, 0x1401

    iget-object v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    move v1, v0

    invoke-static/range {v0 .. v6}, Landroid/opengl/GLES20;->glReadPixels(IIIIIILjava/nio/Buffer;)V

    .line 457
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 458
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {v1, v0}, Ljava/nio/ByteBuffer;->position(I)Ljava/nio/Buffer;

    .line 459
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {p1, v0}, Landroid/graphics/Bitmap;->copyPixelsFromBuffer(Ljava/nio/Buffer;)V

    .line 461
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mTempCanvas:Landroid/graphics/Canvas;

    invoke-virtual {v0, p1}, Landroid/graphics/Canvas;->setBitmap(Landroid/graphics/Bitmap;)V

    .line 464
    invoke-virtual {p2}, Ljava/util/ArrayList;->iterator()Ljava/util/Iterator;

    move-result-object v1

    :cond_0
    :goto_1
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v0

    if-nez v0, :cond_2

    .line 469
    return-void

    .line 443
    :cond_1
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    iget v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    aget v1, v1, v5

    invoke-static {v6, v1}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 444
    invoke-interface {v4}, Ljava/util/ListIterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;

    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-interface {v1, v5}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->draw(Ljava/lang/Object;)V

    .line 445
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    iget v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    aget v1, v1, v5

    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentTexture:I

    .line 448
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    add-int/lit8 v1, v1, 0x1

    rem-int/lit8 v1, v1, 0x2

    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    .line 435
    add-int/lit8 v1, v2, 0x1

    move v2, v1

    goto :goto_0

    .line 464
    :cond_2
    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;

    .line 465
    invoke-interface {v0}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->isOpenGLLayer()Z

    move-result v2

    if-nez v2, :cond_0

    .line 466
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mTempCanvas:Landroid/graphics/Canvas;

    invoke-interface {v0, v2}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->draw(Ljava/lang/Object;)V

    goto :goto_1
.end method

.method public render(Landroid/graphics/Bitmap;Ljava/util/ArrayList;Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;)V
    .locals 9
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Landroid/graphics/Bitmap;",
            "Ljava/util/ArrayList",
            "<",
            "Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;",
            ">;",
            "Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;",
            ")V"
        }
    .end annotation

    .prologue
    const v8, 0x8d40

    const/4 v0, 0x0

    .line 472
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v2

    .line 473
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getHeight()I

    move-result v3

    .line 475
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    if-lt v1, v2, :cond_1

    .line 478
    :goto_0
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    if-lt v1, v3, :cond_2

    .line 483
    :goto_1
    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    .line 485
    invoke-virtual {p2}, Ljava/util/ArrayList;->size()I

    move-result v5

    .line 486
    invoke-virtual {p2}, Ljava/util/ArrayList;->listIterator()Ljava/util/ListIterator;

    move-result-object v6

    move v4, v0

    .line 488
    :goto_2
    add-int/lit8 v1, v5, -0x1

    if-lt v4, v1, :cond_3

    .line 507
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    if-lt v1, v2, :cond_4

    .line 509
    :cond_0
    invoke-virtual {p0, v2, v3, p3}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->setupGlobalTransform(IILcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;)V

    .line 512
    :goto_3
    iget-boolean v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    if-nez v1, :cond_5

    .line 521
    invoke-static {v8, v0}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 523
    :goto_4
    invoke-interface {v6}, Ljava/util/ListIterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;

    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-interface {v1, v4}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->draw(Ljava/lang/Object;)V

    .line 525
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {v1, v0}, Ljava/nio/ByteBuffer;->position(I)Ljava/nio/Buffer;

    const/16 v4, 0x1908

    const/16 v5, 0x1401

    .line 526
    iget-object v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    move v1, v0

    invoke-static/range {v0 .. v6}, Landroid/opengl/GLES20;->glReadPixels(IIIIIILjava/nio/Buffer;)V

    .line 528
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 529
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {v1, v0}, Ljava/nio/ByteBuffer;->position(I)Ljava/nio/Buffer;

    .line 531
    invoke-static {v8, v0}, Landroid/opengl/GLES11Ext;->glBindFramebufferOES(II)V

    .line 532
    invoke-static {v8, v0}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 534
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {p1, v0}, Landroid/graphics/Bitmap;->copyPixelsFromBuffer(Ljava/nio/Buffer;)V

    .line 536
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mTempCanvas:Landroid/graphics/Canvas;

    invoke-virtual {v0, p1}, Landroid/graphics/Canvas;->setBitmap(Landroid/graphics/Bitmap;)V

    .line 537
    invoke-direct {p0, p1}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->addSignatureInfo(Landroid/graphics/Bitmap;)V

    .line 538
    return-void

    .line 476
    :cond_1
    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    goto :goto_0

    .line 479
    :cond_2
    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    goto :goto_1

    .line 496
    :cond_3
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    iget v7, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    aget v1, v1, v7

    invoke-static {v8, v1}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 497
    invoke-interface {v6}, Ljava/util/ListIterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;

    iget-object v7, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-interface {v1, v7}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->draw(Ljava/lang/Object;)V

    .line 498
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    iget v7, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    aget v1, v1, v7

    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentTexture:I

    .line 501
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    add-int/lit8 v1, v1, 0x1

    rem-int/lit8 v1, v1, 0x2

    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    .line 488
    add-int/lit8 v1, v4, 0x1

    move v4, v1

    goto :goto_2

    .line 507
    :cond_4
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    if-ge v1, v3, :cond_0

    goto :goto_3

    .line 514
    :cond_5
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    invoke-static {v8, v1}, Landroid/opengl/GLES11Ext;->glBindFramebufferOES(II)V

    const v1, 0x84c0

    .line 518
    invoke-static {v1}, Landroid/opengl/GLES20;->glActiveTexture(I)V

    goto :goto_4
.end method

.method public resetGlobalTransform()V
    .locals 4

    .prologue
    const/high16 v3, 0x3f800000    # 1.0f

    const/4 v2, 0x0

    .line 576
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-static {v0, v2}, Landroid/opengl/Matrix;->setIdentityM([FI)V

    .line 577
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    const/high16 v1, -0x40800000    # -1.0f

    invoke-static {v0, v2, v3, v1, v3}, Landroid/opengl/Matrix;->scaleM([FIFFF)V

    .line 578
    iget-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    if-nez v0, :cond_0

    .line 582
    :goto_0
    return-void

    :cond_0
    const/16 v0, 0xc11

    .line 579
    invoke-static {v0}, Landroid/opengl/GLES20;->glDisable(I)V

    .line 580
    iput-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    goto :goto_0
.end method

.method public restoreContextIfNeeded()V
    .locals 6

    .prologue
    const/4 v5, 0x0

    .line 294
    iget-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    if-nez v0, :cond_0

    .line 304
    :goto_0
    return-void

    .line 295
    :cond_0
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v0, v1, v2, v3, v4}, Ljavax/microedition/khronos/egl/EGL10;->eglMakeCurrent(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLContext;)Z

    move-result v0

    if-nez v0, :cond_1

    .line 299
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->TAG:Ljava/lang/String;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string/jumbo v2, " disp: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string/jumbo v2, " Can\'t restore original context, err: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v2}, Ljavax/microedition/khronos/egl/EGL10;->eglGetError()I

    move-result v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string/jumbo v2, " maybe was no context bound before."

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Landroid/util/Log;->e(Ljava/lang/String;Ljava/lang/String;)I

    goto :goto_0

    .line 297
    :cond_1
    iput-boolean v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    goto :goto_0
.end method

.method public setupGlobalTransform(IILcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;)V
    .locals 9

    .prologue
    const/16 v8, 0xc11

    const/high16 v7, -0x40800000    # -1.0f

    const/high16 v6, 0x3f800000    # 1.0f

    const/high16 v5, 0x40000000    # 2.0f

    const/4 v4, 0x0

    .line 545
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-static {v0, v4}, Landroid/opengl/Matrix;->setIdentityM([FI)V

    .line 547
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$1;->$SwitchMap$com$sonymobile$generativeartwork$render$OffscreenRenderer$Mode:[I

    invoke-virtual {p3}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;->ordinal()I

    move-result v1

    aget v0, v0, v1

    packed-switch v0, :pswitch_data_0

    .line 573
    :cond_0
    :goto_0
    return-void

    .line 550
    :pswitch_0
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    sub-int v1, p1, v1

    int-to-float v1, v1

    div-float/2addr v1, v5

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    int-to-float v2, v2

    div-float/2addr v1, v2

    mul-float/2addr v1, v5

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    sub-int v2, p2, v2

    int-to-float v2, v2

    div-float/2addr v2, v5

    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    int-to-float v3, v3

    div-float/2addr v2, v3

    mul-float/2addr v2, v5

    const/4 v3, 0x0

    invoke-static {v0, v4, v1, v2, v3}, Landroid/opengl/Matrix;->translateM([FIFFF)V

    .line 554
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    int-to-float v1, p1

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    int-to-float v2, v2

    div-float/2addr v1, v2

    int-to-float v2, p2

    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    int-to-float v3, v3

    div-float/2addr v2, v3

    mul-float/2addr v2, v7

    invoke-static {v0, v4, v1, v2, v6}, Landroid/opengl/Matrix;->scaleM([FIFFF)V

    .line 558
    iget-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    if-eqz v0, :cond_0

    .line 559
    invoke-static {v8}, Landroid/opengl/GLES20;->glDisable(I)V

    .line 560
    iput-boolean v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    goto :goto_0

    .line 565
    :pswitch_1
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-static {v0, v4, v6, v7, v6}, Landroid/opengl/Matrix;->scaleM([FIFFF)V

    .line 566
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    if-gt p1, v0, :cond_0

    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    if-gt p2, v0, :cond_0

    .line 567
    invoke-static {v4, v4, p1, p2}, Landroid/opengl/GLES20;->glScissor(IIII)V

    .line 568
    invoke-static {v8}, Landroid/opengl/GLES20;->glEnable(I)V

    .line 569
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    goto :goto_0

    .line 547
    nop

    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_0
        :pswitch_1
    .end packed-switch
.end method
