.class public Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;
.super Ljava/lang/Object;
.source "OffscreenRenderer.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$1;,
        Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;
    }
.end annotation


# static fields
.field private static OES_TEXTURE_IDX:I

.field private static final TAG:Ljava/lang/String;

.field static final mNumSignaturePxls:I

.field static final mSignatureData:[B

.field static final mSignatureLength:I


# instance fields
.field private isOESFBSupported:Z

.field private mClearingBits:I

.field private mConfigSpec:[I

.field private mCurrentFB:I

.field private mCurrentTexture:I

.field private mEgl:Ljavax/microedition/khronos/egl/EGL10;

.field private mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

.field private mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

.field private mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

.field private mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

.field private mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

.field private mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

.field private mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

.field private mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

.field private mFBO:[I

.field private mGlobalTransform:[F

.field private mHeight:I

.field private mNeedContextSwitch:Z

.field private mOESFBO:I

.field private mOffscreenTexture:[I

.field private mPBO:I

.field private mPBOSize:I

.field private mResBuffer:Ljava/nio/ByteBuffer;

.field private mScissorsEnabled:Z

.field private mSignaturePixels:[I

.field private mTempCanvas:Landroid/graphics/Canvas;

.field private mWidth:I


# direct methods
.method static constructor <clinit>()V
    .locals 2

    .prologue
    const-class v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;

    .line 53
    invoke-virtual {v0}, Ljava/lang/Class;->getName()Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->TAG:Ljava/lang/String;

    const/4 v0, 0x2

    .line 60
    sput v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->OES_TEXTURE_IDX:I

    const-string/jumbo v0, "Generated by Sony GAW:1.0"

    const-string/jumbo v1, "US-ASCII"

    .line 80
    invoke-static {v1}, Ljava/nio/charset/Charset;->forName(Ljava/lang/String;)Ljava/nio/charset/Charset;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/String;->getBytes(Ljava/nio/charset/Charset;)[B

    move-result-object v0

    sput-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    .line 81
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    array-length v0, v0

    sput v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    .line 82
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    mul-int/lit8 v0, v0, 0x2

    sput v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    return-void
.end method

.method public constructor <init>()V
    .locals 4

    .prologue
    const/4 v1, -0x1

    const/high16 v3, 0x3f800000    # 1.0f

    const/4 v2, 0x0

    .line 136
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 83
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    new-array v0, v0, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    const/4 v0, 0x3

    .line 85
    new-array v0, v0, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    const/4 v0, 0x2

    .line 87
    new-array v0, v0, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    .line 89
    iput-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    .line 90
    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    .line 92
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    .line 94
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentTexture:I

    .line 96
    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBO:I

    .line 98
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBOSize:I

    .line 104
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_DISPLAY:Ljavax/microedition/khronos/egl/EGLDisplay;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 106
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 108
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 110
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 112
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 114
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 116
    sget-object v0, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_DISPLAY:Ljavax/microedition/khronos/egl/EGLDisplay;

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 118
    iput-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    .line 122
    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    const/16 v0, 0x10

    .line 133
    new-array v0, v0, [F

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    .line 134
    iput-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    .line 137
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-static {v0, v2}, Landroid/opengl/Matrix;->setIdentityM([FI)V

    .line 138
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    const/high16 v1, -0x40800000    # -1.0f

    invoke-static {v0, v2, v3, v1, v3}, Landroid/opengl/Matrix;->scaleM([FIFFF)V

    .line 140
    new-instance v0, Landroid/graphics/Canvas;

    invoke-direct {v0}, Landroid/graphics/Canvas;-><init>()V

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mTempCanvas:Landroid/graphics/Canvas;

    .line 141
    return-void
.end method

.method private addSignatureInfo(Landroid/graphics/Bitmap;)V
    .locals 12
    .param p1, "img"    # Landroid/graphics/Bitmap;

    .prologue
    const v11, -0x1010102

    const/4 v2, 0x0

    .line 587
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    mul-int/lit8 v0, v0, 0x8

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getByteCount()I

    move-result v1

    mul-int/lit8 v1, v1, 0x4

    if-lt v0, v1, :cond_0

    .line 626
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "Too large string for hiding"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 588
    :cond_0
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v1

    if-gt v0, v1, :cond_2

    sget v6, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    .line 591
    .local v6, "width":I
    :goto_0
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v1

    div-int v7, v0, v1

    .line 592
    .local v7, "height":I
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v1

    rem-int/2addr v0, v1

    if-nez v0, :cond_3

    .line 595
    :goto_1
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getHeight()I

    move-result v0

    if-gt v7, v0, :cond_4

    .line 601
    :goto_2
    mul-int v10, v6, v7

    .line 602
    .local v10, "numPixels":I
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNumSignaturePxls:I

    if-lt v0, v10, :cond_5

    .line 606
    :cond_1
    :goto_3
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    move-object v0, p1

    move v4, v2

    move v5, v2

    invoke-virtual/range {v0 .. v7}, Landroid/graphics/Bitmap;->getPixels([IIIIIII)V

    const/4 v8, 0x0

    .local v8, "chnlPxlIdx":I
    const/4 v9, 0x0

    .line 608
    .local v9, "i":I
    :goto_4
    sget v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureLength:I

    if-lt v9, v0, :cond_6

    .line 624
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v3

    move-object v0, p1

    move v4, v2

    move v5, v2

    invoke-virtual/range {v0 .. v7}, Landroid/graphics/Bitmap;->setPixels([IIIIIII)V

    .line 628
    return-void

    .line 588
    .end local v6    # "width":I
    .end local v7    # "height":I
    .end local v8    # "chnlPxlIdx":I
    .end local v9    # "i":I
    .end local v10    # "numPixels":I
    :cond_2
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v6

    goto :goto_0

    .line 593
    .restart local v6    # "width":I
    .restart local v7    # "height":I
    :cond_3
    add-int/lit8 v7, v7, 0x1

    goto :goto_1

    .line 595
    :cond_4
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getHeight()I

    move-result v7

    goto :goto_2

    .line 602
    .restart local v10    # "numPixels":I
    :cond_5
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    array-length v0, v0

    if-ge v0, v10, :cond_1

    .line 603
    new-array v0, v10, [I

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    goto :goto_3

    .line 609
    .restart local v8    # "chnlPxlIdx":I
    .restart local v9    # "i":I
    :cond_6
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v1, v8, 0x1

    aget v3, v0, v1

    and-int/2addr v3, v11

    aput v3, v0, v1

    .line 610
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v1, v8, 0x1

    aget v3, v0, v1

    sget-object v4, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v4, v4, v9

    shr-int/lit8 v4, v4, 0x0

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x0

    or-int/2addr v3, v4

    aput v3, v0, v1

    .line 611
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v1, v8, 0x1

    aget v3, v0, v1

    sget-object v4, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v4, v4, v9

    shr-int/lit8 v4, v4, 0x1

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x8

    or-int/2addr v3, v4

    aput v3, v0, v1

    .line 612
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v1, v8, 0x1

    aget v3, v0, v1

    sget-object v4, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v4, v4, v9

    shr-int/lit8 v4, v4, 0x2

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x10

    or-int/2addr v3, v4

    aput v3, v0, v1

    .line 613
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    add-int/lit8 v1, v8, 0x1

    aget v3, v0, v1

    sget-object v4, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v4, v4, v9

    shr-int/lit8 v4, v4, 0x3

    and-int/lit8 v4, v4, 0x1

    shl-int/lit8 v4, v4, 0x18

    or-int/2addr v3, v4

    aput v3, v0, v1

    .line 615
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v1, v0, v8

    and-int/2addr v1, v11

    aput v1, v0, v8

    .line 616
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v1, v0, v8

    sget-object v3, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v3, v3, v9

    shr-int/lit8 v3, v3, 0x4

    and-int/lit8 v3, v3, 0x1

    shl-int/lit8 v3, v3, 0x0

    or-int/2addr v1, v3

    aput v1, v0, v8

    .line 617
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v1, v0, v8

    sget-object v3, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v3, v3, v9

    shr-int/lit8 v3, v3, 0x5

    and-int/lit8 v3, v3, 0x1

    shl-int/lit8 v3, v3, 0x8

    or-int/2addr v1, v3

    aput v1, v0, v8

    .line 618
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v1, v0, v8

    sget-object v3, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v3, v3, v9

    shr-int/lit8 v3, v3, 0x6

    and-int/lit8 v3, v3, 0x1

    shl-int/lit8 v3, v3, 0x10

    or-int/2addr v1, v3

    aput v1, v0, v8

    .line 619
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignaturePixels:[I

    aget v1, v0, v8

    sget-object v3, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mSignatureData:[B

    aget-byte v3, v3, v9

    shr-int/lit8 v3, v3, 0x7

    and-int/lit8 v3, v3, 0x1

    shl-int/lit8 v3, v3, 0x18

    or-int/2addr v1, v3

    aput v1, v0, v8

    .line 621
    add-int/lit8 v8, v8, 0x2

    .line 608
    add-int/lit8 v9, v9, 0x1

    goto/16 :goto_4
.end method

.method private chooseConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;)Ljavax/microedition/khronos/egl/EGLConfig;
    .locals 7
    .param p1, "egl"    # Ljavax/microedition/khronos/egl/EGL10;
    .param p2, "display"    # Ljavax/microedition/khronos/egl/EGLDisplay;

    .prologue
    const/4 v3, 0x0

    const/4 v4, 0x0

    const/4 v0, 0x1

    .line 309
    new-array v5, v0, [I

    .line 311
    .local v5, "num_config":[I
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    move-object v0, p1

    move-object v1, p2

    invoke-interface/range {v0 .. v5}, Ljavax/microedition/khronos/egl/EGL10;->eglChooseConfig(Ljavax/microedition/khronos/egl/EGLDisplay;[I[Ljavax/microedition/khronos/egl/EGLConfig;I[I)Z

    move-result v0

    if-eqz v0, :cond_0

    .line 315
    aget v4, v5, v4

    .line 316
    .local v4, "numConfigs":I
    if-lez v4, :cond_1

    .line 321
    new-array v3, v4, [Ljavax/microedition/khronos/egl/EGLConfig;

    .line 322
    .local v3, "configs":[Ljavax/microedition/khronos/egl/EGLConfig;
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    move-object v0, p1

    move-object v1, p2

    invoke-interface/range {v0 .. v5}, Ljavax/microedition/khronos/egl/EGL10;->eglChooseConfig(Ljavax/microedition/khronos/egl/EGLDisplay;[I[Ljavax/microedition/khronos/egl/EGLConfig;I[I)Z

    move-result v0

    if-eqz v0, :cond_2

    .line 326
    invoke-direct {p0, p1, p2, v3}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;[Ljavax/microedition/khronos/egl/EGLConfig;)Ljavax/microedition/khronos/egl/EGLConfig;

    move-result-object v6

    .line 327
    .local v6, "config":Ljavax/microedition/khronos/egl/EGLConfig;
    if-eqz v6, :cond_3

    .line 330
    return-object v6

    .line 312
    .end local v3    # "configs":[Ljavax/microedition/khronos/egl/EGLConfig;
    .end local v4    # "numConfigs":I
    .end local v6    # "config":Ljavax/microedition/khronos/egl/EGLConfig;
    :cond_0
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "eglChooseConfig failed"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 317
    .restart local v4    # "numConfigs":I
    :cond_1
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "No configs match configSpec"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 323
    .restart local v3    # "configs":[Ljavax/microedition/khronos/egl/EGLConfig;
    :cond_2
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "eglChooseConfig#2 failed"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 328
    .restart local v6    # "config":Ljavax/microedition/khronos/egl/EGLConfig;
    :cond_3
    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string/jumbo v1, "No config chosen"

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method private createOffscreenBuffs()V
    .locals 14

    .prologue
    const/4 v13, 0x2

    const/4 v12, 0x3

    const v11, 0x8d40

    const/16 v0, 0xde1

    const/4 v1, 0x0

    .line 365
    new-array v10, v12, [I

    .line 368
    .local v10, "tmpName":[I
    invoke-static {v12, v10, v1}, Landroid/opengl/GLES20;->glGenTextures(I[II)V

    .line 369
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const v2, 0x84c0

    .line 370
    invoke-static {v2}, Landroid/opengl/GLES20;->glActiveTexture(I)V

    .line 371
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/4 v9, 0x0

    .line 373
    .local v9, "i":I
    :goto_0
    if-lt v9, v12, :cond_0

    .line 393
    invoke-static {v13, v10, v1}, Landroid/opengl/GLES20;->glGenFramebuffers(I[II)V

    .line 394
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/4 v9, 0x0

    .line 396
    :goto_1
    if-lt v9, v13, :cond_1

    .line 408
    iget-boolean v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    if-nez v2, :cond_2

    .line 424
    :goto_2
    invoke-static {v11, v1}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 425
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 426
    return-void

    .line 374
    :cond_0
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    aget v3, v10, v9

    aput v3, v2, v9

    .line 376
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    aget v2, v2, v9

    invoke-static {v0, v2}, Landroid/opengl/GLES20;->glBindTexture(II)V

    .line 377
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x1908

    .line 378
    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    const/16 v6, 0x1908

    const/16 v7, 0x1401

    const/4 v8, 0x0

    move v5, v1

    invoke-static/range {v0 .. v8}, Landroid/opengl/GLES20;->glTexImage2D(IIIIIIIILjava/nio/Buffer;)V

    .line 380
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2801

    const/16 v3, 0x2600

    .line 381
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 383
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2800

    const/16 v3, 0x2600

    .line 384
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 386
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2802

    const/16 v3, 0x2901

    .line 387
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 388
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const/16 v2, 0x2803

    const/16 v3, 0x2901

    .line 389
    invoke-static {v0, v2, v3}, Landroid/opengl/GLES20;->glTexParameteri(III)V

    .line 390
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 373
    add-int/lit8 v9, v9, 0x1

    goto :goto_0

    .line 397
    :cond_1
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    aget v3, v10, v9

    aput v3, v2, v9

    .line 399
    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    aget v2, v2, v9

    invoke-static {v11, v2}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 400
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const v2, 0x8ce0

    .line 401
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    aget v3, v3, v9

    invoke-static {v11, v2, v0, v3, v1}, Landroid/opengl/GLES20;->glFramebufferTexture2D(IIIII)V

    .line 403
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 404
    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    invoke-static {v1, v1, v2, v3}, Landroid/opengl/GLES20;->glViewport(IIII)V

    .line 405
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 396
    add-int/lit8 v9, v9, 0x1

    goto/16 :goto_1

    :cond_2
    const/4 v2, 0x1

    .line 410
    invoke-static {v2, v10, v1}, Landroid/opengl/GLES11Ext;->glGenFramebuffersOES(I[II)V

    .line 411
    aget v2, v10, v1

    iput v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    .line 413
    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    invoke-static {v11, v2}, Landroid/opengl/GLES11Ext;->glBindFramebufferOES(II)V

    .line 414
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    const v2, 0x8ce0

    .line 415
    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    sget v4, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->OES_TEXTURE_IDX:I

    aget v3, v3, v4

    invoke-static {v11, v2, v0, v3, v1}, Landroid/opengl/GLES11Ext;->glFramebufferTexture2DOES(IIIII)V

    .line 420
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 421
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    invoke-static {v1, v1, v0, v2}, Landroid/opengl/GLES20;->glViewport(IIII)V

    .line 422
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    goto/16 :goto_2
.end method

.method private findConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;[Ljavax/microedition/khronos/egl/EGLConfig;)Ljavax/microedition/khronos/egl/EGLConfig;
    .locals 15
    .param p1, "egl"    # Ljavax/microedition/khronos/egl/EGL10;
    .param p2, "display"    # Ljavax/microedition/khronos/egl/EGLDisplay;
    .param p3, "configs"    # [Ljavax/microedition/khronos/egl/EGLConfig;

    .prologue
    .line 334
    move-object/from16 v7, p3

    .local v7, "arr$":[Ljavax/microedition/khronos/egl/EGLConfig;
    array-length v12, v7

    .local v12, "len$":I
    const/4 v11, 0x0

    .local v11, "i$":I
    :goto_0
    if-lt v11, v12, :cond_0

    const/4 v0, 0x0

    .line 349
    return-object v0

    .line 334
    :cond_0
    aget-object v3, v7, v11

    .local v3, "config":Ljavax/microedition/khronos/egl/EGLConfig;
    const/16 v4, 0x3025

    const/4 v5, 0x0

    move-object v0, p0

    move-object/from16 v1, p1

    move-object/from16 v2, p2

    .line 335
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v9

    .local v9, "d":I
    const/16 v4, 0x3026

    const/4 v5, 0x0

    move-object v0, p0

    move-object/from16 v1, p1

    move-object/from16 v2, p2

    .line 336
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v14

    .line 337
    .local v14, "s":I
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/16 v1, 0x9

    aget v0, v0, v1

    if-ge v9, v0, :cond_2

    .line 334
    :cond_1
    add-int/lit8 v11, v11, 0x1

    goto :goto_0

    .line 337
    :cond_2
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/16 v1, 0xb

    aget v0, v0, v1

    if-lt v14, v0, :cond_1

    const/16 v4, 0x3024

    const/4 v5, 0x0

    move-object v0, p0

    move-object/from16 v1, p1

    move-object/from16 v2, p2

    .line 338
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v13

    .local v13, "r":I
    const/16 v4, 0x3023

    const/4 v5, 0x0

    move-object v0, p0

    move-object/from16 v1, p1

    move-object/from16 v2, p2

    .line 339
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v10

    .local v10, "g":I
    const/16 v4, 0x3022

    const/4 v5, 0x0

    move-object v0, p0

    move-object/from16 v1, p1

    move-object/from16 v2, p2

    .line 340
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v8

    .local v8, "b":I
    const/16 v4, 0x3021

    const/4 v5, 0x0

    move-object v0, p0

    move-object/from16 v1, p1

    move-object/from16 v2, p2

    .line 341
    invoke-direct/range {v0 .. v5}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I

    move-result v6

    .line 342
    .local v6, "a":I
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v1, 0x1

    aget v0, v0, v1

    if-ne v13, v0, :cond_1

    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v1, 0x3

    aget v0, v0, v1

    if-ne v10, v0, :cond_1

    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v1, 0x5

    aget v0, v0, v1

    if-ne v8, v0, :cond_1

    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/4 v1, 0x7

    aget v0, v0, v1

    if-ne v6, v0, :cond_1

    .line 345
    return-object v3
.end method

.method private findConfigAttrib(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;II)I
    .locals 3
    .param p1, "egl"    # Ljavax/microedition/khronos/egl/EGL10;
    .param p2, "display"    # Ljavax/microedition/khronos/egl/EGLDisplay;
    .param p3, "config"    # Ljavax/microedition/khronos/egl/EGLConfig;
    .param p4, "attribute"    # I
    .param p5, "defaultValue"    # I

    .prologue
    const/4 v2, 0x0

    const/4 v1, 0x1

    .line 355
    new-array v0, v1, [I

    .line 356
    .local v0, "value":[I
    invoke-interface {p1, p2, p3, p4, v0}, Ljavax/microedition/khronos/egl/EGL10;->eglGetConfigAttrib(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;I[I)Z

    move-result v1

    if-nez v1, :cond_0

    .line 359
    return p5

    .line 357
    :cond_0
    aget v1, v0, v2

    return v1
.end method


# virtual methods
.method public getCurrentTexture()I
    .locals 1

    .prologue
    .line 543
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentTexture:I

    return v0
.end method

.method public init(IIIIIIII)V
    .locals 9
    .param p1, "redSize"    # I
    .param p2, "greenSize"    # I
    .param p3, "blueSize"    # I
    .param p4, "alphaSize"    # I
    .param p5, "depthSize"    # I
    .param p6, "stencilSize"    # I
    .param p7, "width"    # I
    .param p8, "height"    # I

    .prologue
    .line 148
    move/from16 v0, p7

    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    .line 149
    move/from16 v0, p8

    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    .line 154
    invoke-static {}, Ljavax/microedition/khronos/egl/EGLContext;->getEGL()Ljavax/microedition/khronos/egl/EGL;

    move-result-object v5

    check-cast v5, Ljavax/microedition/khronos/egl/EGL10;

    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    .line 159
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    sget-object v6, Ljavax/microedition/khronos/egl/EGL10;->EGL_DEFAULT_DISPLAY:Ljava/lang/Object;

    invoke-interface {v5, v6}, Ljavax/microedition/khronos/egl/EGL10;->eglGetDisplay(Ljava/lang/Object;)Ljavax/microedition/khronos/egl/EGLDisplay;

    move-result-object v5

    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 160
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    sget-object v6, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_DISPLAY:Ljavax/microedition/khronos/egl/EGLDisplay;

    if-eq v5, v6, :cond_1

    const/4 v5, 0x2

    .line 167
    new-array v4, v5, [I

    .line 168
    .local v4, "version":[I
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-interface {v5, v6, v4}, Ljavax/microedition/khronos/egl/EGL10;->eglInitialize(Ljavax/microedition/khronos/egl/EGLDisplay;[I)Z

    move-result v5

    if-eqz v5, :cond_2

    const/16 v5, 0x15

    .line 175
    new-array v5, v5, [I

    const/4 v6, 0x0

    const/16 v7, 0x3024

    aput v7, v5, v6

    const/4 v6, 0x1

    aput p1, v5, v6

    const/4 v6, 0x2

    const/16 v7, 0x3023

    aput v7, v5, v6

    const/4 v6, 0x3

    aput p2, v5, v6

    const/4 v6, 0x4

    const/16 v7, 0x3022

    aput v7, v5, v6

    const/4 v6, 0x5

    aput p3, v5, v6

    const/4 v6, 0x6

    const/16 v7, 0x3021

    aput v7, v5, v6

    const/4 v6, 0x7

    aput p4, v5, v6

    const/16 v6, 0x8

    const/16 v7, 0x3025

    aput v7, v5, v6

    const/16 v6, 0x9

    aput p5, v5, v6

    const/16 v6, 0xa

    const/16 v7, 0x3026

    aput v7, v5, v6

    const/16 v6, 0xb

    aput p6, v5, v6

    const/16 v6, 0xc

    const/16 v7, 0x3033

    aput v7, v5, v6

    const/16 v6, 0xd

    const/4 v7, 0x1

    aput v7, v5, v6

    const/16 v6, 0xe

    const/16 v7, 0x3042

    aput v7, v5, v6

    const/16 v6, 0xf

    const/4 v7, 0x4

    aput v7, v5, v6

    const/16 v6, 0x10

    const/16 v7, 0x3040

    aput v7, v5, v6

    const/16 v6, 0x11

    const/4 v7, 0x4

    aput v7, v5, v6

    const/16 v6, 0x12

    const/16 v7, 0x303a

    aput v7, v5, v6

    const/16 v6, 0x13

    const/4 v7, 0x1

    aput v7, v5, v6

    const/16 v6, 0x14

    const/16 v7, 0x3038

    aput v7, v5, v6

    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mConfigSpec:[I

    const/16 v5, 0x4000

    .line 192
    iput v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    .line 193
    if-nez p5, :cond_3

    .line 197
    :goto_0
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-direct {p0, v5, v6}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->chooseConfig(Ljavax/microedition/khronos/egl/EGL10;Ljavax/microedition/khronos/egl/EGLDisplay;)Ljavax/microedition/khronos/egl/EGLConfig;

    move-result-object v5

    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

    const/4 v5, 0x3

    .line 204
    new-array v1, v5, [I

    const/4 v5, 0x0

    const/16 v6, 0x3098

    aput v6, v1, v5

    const/4 v5, 0x1

    const/4 v6, 0x2

    aput v6, v1, v5

    const/4 v5, 0x2

    const/16 v6, 0x3038

    aput v6, v1, v5

    .line 207
    .local v1, "context_attrib_list":[I
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v7, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

    sget-object v8, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v5, v6, v7, v8, v1}, Ljavax/microedition/khronos/egl/EGL10;->eglCreateContext(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;Ljavax/microedition/khronos/egl/EGLContext;[I)Ljavax/microedition/khronos/egl/EGLContext;

    move-result-object v5

    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 209
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    if-nez v5, :cond_4

    :cond_0
    const/4 v5, 0x0

    .line 210
    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 211
    new-instance v5, Ljava/lang/RuntimeException;

    const-string/jumbo v6, "eglCreateContext failed"

    invoke-direct {v5, v6}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v5

    .line 161
    .end local v1    # "context_attrib_list":[I
    .end local v4    # "version":[I
    :cond_1
    new-instance v5, Ljava/lang/RuntimeException;

    const-string/jumbo v6, "eglGetDisplay failed"

    invoke-direct {v5, v6}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v5

    .line 169
    .restart local v4    # "version":[I
    :cond_2
    new-instance v5, Ljava/lang/RuntimeException;

    const-string/jumbo v6, "eglInitialize failed"

    invoke-direct {v5, v6}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v5

    .line 194
    :cond_3
    iget v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    or-int/lit16 v5, v5, 0x100

    iput v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mClearingBits:I

    goto :goto_0

    .line 209
    .restart local v1    # "context_attrib_list":[I
    :cond_4
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    sget-object v6, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_CONTEXT:Ljavax/microedition/khronos/egl/EGLContext;

    if-eq v5, v6, :cond_0

    .line 216
    iget v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    iget v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    mul-int/2addr v5, v6

    mul-int/lit8 v5, v5, 0x4

    iput v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBOSize:I

    .line 217
    iget v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mPBOSize:I

    invoke-static {v5}, Ljava/nio/ByteBuffer;->allocateDirect(I)Ljava/nio/ByteBuffer;

    move-result-object v5

    invoke-static {}, Ljava/nio/ByteOrder;->nativeOrder()Ljava/nio/ByteOrder;

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/nio/ByteBuffer;->order(Ljava/nio/ByteOrder;)Ljava/nio/ByteBuffer;

    move-result-object v5

    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    const/16 v5, 0x9

    .line 222
    new-array v3, v5, [I

    const/4 v5, 0x0

    const/16 v6, 0x3057

    aput v6, v3, v5

    const/4 v5, 0x1

    iget v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    aput v6, v3, v5

    const/4 v5, 0x2

    const/16 v6, 0x3056

    aput v6, v3, v5

    const/4 v5, 0x3

    iget v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    aput v6, v3, v5

    const/4 v5, 0x4

    const/16 v6, 0x3080

    aput v6, v3, v5

    const/4 v5, 0x5

    const/16 v6, 0x305e

    aput v6, v3, v5

    const/4 v5, 0x6

    const/16 v6, 0x3081

    aput v6, v3, v5

    const/4 v5, 0x7

    const/16 v6, 0x305f

    aput v6, v3, v5

    const/16 v5, 0x8

    const/16 v6, 0x3038

    aput v6, v3, v5

    .line 227
    .local v3, "pbuffer_attrib_list":[I
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v7, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglConfig:Ljavax/microedition/khronos/egl/EGLConfig;

    invoke-interface {v5, v6, v7, v3}, Ljavax/microedition/khronos/egl/EGL10;->eglCreatePbufferSurface(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;[I)Ljavax/microedition/khronos/egl/EGLSurface;

    move-result-object v5

    iput-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 228
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    if-nez v5, :cond_6

    .line 229
    :cond_5
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v5}, Ljavax/microedition/khronos/egl/EGL10;->eglGetError()I

    move-result v2

    .local v2, "error":I
    const/16 v5, 0x300b

    .line 230
    if-eq v2, v5, :cond_7

    .line 235
    .end local v2    # "error":I
    :goto_1
    invoke-virtual {p0}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->makeCurrentIfNeeded()V

    const/16 v5, 0x1f03

    .line 237
    invoke-static {v5}, Landroid/opengl/GLES20;->glGetString(I)Ljava/lang/String;

    move-result-object v5

    const-string/jumbo v6, "GL_OES_framebuffer_object"

    invoke-virtual {v5, v6}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v5

    iput-boolean v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    const/high16 v5, 0x3e800000    # 0.25f

    const/high16 v6, 0x3e800000    # 0.25f

    const/high16 v7, 0x3e800000    # 0.25f

    const/high16 v8, 0x3f800000    # 1.0f

    .line 241
    invoke-static {v5, v6, v7, v8}, Landroid/opengl/GLES20;->glClearColor(FFFF)V

    .line 243
    invoke-direct {p0}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->createOffscreenBuffs()V

    .line 244
    return-void

    .line 228
    :cond_6
    iget-object v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    sget-object v6, Ljavax/microedition/khronos/egl/EGL10;->EGL_NO_SURFACE:Ljavax/microedition/khronos/egl/EGLSurface;

    if-eq v5, v6, :cond_5

    goto :goto_1

    .line 231
    .restart local v2    # "error":I
    :cond_7
    new-instance v5, Ljava/lang/RuntimeException;

    const-string/jumbo v6, "eglCreatePbufferSurface has failed"

    invoke-direct {v5, v6}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v5
.end method

.method public makeCurrentIfNeeded()V
    .locals 5

    .prologue
    .line 277
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v0}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentContext()Ljavax/microedition/khronos/egl/EGLContext;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    .line 278
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    const/16 v1, 0x3059

    invoke-interface {v0, v1}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentSurface(I)Ljavax/microedition/khronos/egl/EGLSurface;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 279
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    const/16 v1, 0x305a

    invoke-interface {v0, v1}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentSurface(I)Ljavax/microedition/khronos/egl/EGLSurface;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    .line 280
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v0}, Ljavax/microedition/khronos/egl/EGL10;->eglGetCurrentDisplay()Ljavax/microedition/khronos/egl/EGLDisplay;

    move-result-object v0

    iput-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    .line 282
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    if-eq v0, v1, :cond_1

    .line 286
    :cond_0
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v0, v1, v2, v3, v4}, Ljavax/microedition/khronos/egl/EGL10;->eglMakeCurrent(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLContext;)Z

    move-result v0

    if-nez v0, :cond_2

    .line 289
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->TAG:Ljava/lang/String;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string/jumbo v2, "Can\'t perform context switch, err: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v2}, Ljavax/microedition/khronos/egl/EGL10;->eglGetError()I

    move-result v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Landroid/util/Log;->e(Ljava/lang/String;Ljava/lang/String;)I

    .line 292
    :goto_0
    return-void

    .line 282
    :cond_1
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    if-ne v0, v1, :cond_0

    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    if-ne v0, v1, :cond_0

    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    if-ne v0, v1, :cond_0

    goto :goto_0

    .line 287
    :cond_2
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    goto :goto_0
.end method

.method public release()V
    .locals 5

    .prologue
    const/4 v4, 0x2

    const/4 v3, 0x3

    const/4 v2, 0x0

    .line 250
    new-array v0, v3, [I

    .line 255
    .local v0, "tmpName":[I
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    invoke-static {v1, v2, v0, v2, v4}, Ljava/lang/System;->arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V

    .line 256
    invoke-static {v4, v0, v2}, Landroid/opengl/GLES20;->glDeleteFramebuffers(I[II)V

    .line 257
    iget-boolean v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    if-nez v1, :cond_0

    .line 262
    :goto_0
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    invoke-static {v1, v2, v0, v2, v3}, Ljava/lang/System;->arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V

    .line 263
    invoke-static {v3, v0, v2}, Landroid/opengl/GLES20;->glDeleteTextures(I[II)V

    .line 264
    invoke-virtual {p0}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->restoreContextIfNeeded()V

    .line 267
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglSurface:Ljavax/microedition/khronos/egl/EGLSurface;

    invoke-interface {v1, v2, v3}, Ljavax/microedition/khronos/egl/EGL10;->eglDestroySurface(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLSurface;)Z

    .line 269
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglContext:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v1, v2, v3}, Ljavax/microedition/khronos/egl/EGL10;->eglDestroyContext(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLContext;)Z

    .line 271
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-interface {v1, v2}, Ljavax/microedition/khronos/egl/EGL10;->eglTerminate(Ljavax/microedition/khronos/egl/EGLDisplay;)Z

    .line 272
    return-void

    .line 258
    :cond_0
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    aput v1, v0, v2

    const/4 v1, 0x1

    .line 259
    invoke-static {v1, v0, v2}, Landroid/opengl/GLES11Ext;->glDeleteFramebuffersOES(I[II)V

    goto :goto_0
.end method

.method public render(Landroid/graphics/Bitmap;Ljava/util/ArrayList;Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;)V
    .locals 11
    .param p1, "resultingImage"    # Landroid/graphics/Bitmap;
    .param p3, "mode"    # Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Landroid/graphics/Bitmap;",
            "Ljava/util/ArrayList",
            "<",
            "Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;",
            ">;",
            "Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;",
            ")V"
        }
    .end annotation

    .prologue
    .local p2, "layers":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;>;"
    const v10, 0x8d40

    const/4 v0, 0x0

    .line 474
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getWidth()I

    move-result v2

    .line 475
    .local v2, "width":I
    invoke-virtual {p1}, Landroid/graphics/Bitmap;->getHeight()I

    move-result v3

    .line 477
    .local v3, "height":I
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    if-lt v1, v2, :cond_1

    .line 480
    :goto_0
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    if-lt v1, v3, :cond_2

    .line 485
    :goto_1
    iput v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    const/4 v8, 0x0

    .line 487
    .local v8, "layerNumber":I
    invoke-virtual {p2}, Ljava/util/ArrayList;->size()I

    move-result v9

    .line 488
    .local v9, "lyersCount":I
    invoke-virtual {p2}, Ljava/util/ArrayList;->listIterator()Ljava/util/ListIterator;

    move-result-object v7

    .local v7, "iter":Ljava/util/ListIterator;, "Ljava/util/ListIterator<Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;>;"
    const/4 v8, 0x0

    .line 490
    :goto_2
    add-int/lit8 v1, v9, -0x1

    if-lt v8, v1, :cond_3

    .line 509
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    if-lt v1, v2, :cond_4

    .line 511
    :cond_0
    invoke-virtual {p0, v2, v3, p3}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->setupGlobalTransform(IILcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;)V

    .line 514
    :goto_3
    iget-boolean v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->isOESFBSupported:Z

    if-nez v1, :cond_5

    .line 523
    invoke-static {v10, v0}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 525
    :goto_4
    invoke-interface {v7}, Ljava/util/ListIterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;

    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-interface {v1, v4}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->draw(Ljava/lang/Object;)V

    .line 527
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {v1, v0}, Ljava/nio/ByteBuffer;->position(I)Ljava/nio/Buffer;

    const/16 v4, 0x1908

    const/16 v5, 0x1401

    .line 528
    iget-object v6, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    move v1, v0

    invoke-static/range {v0 .. v6}, Landroid/opengl/GLES20;->glReadPixels(IIIIIILjava/nio/Buffer;)V

    .line 530
    invoke-static {}, Lcom/sonymobile/generativeartwork/utils/Utils;->checkGLErr()V

    .line 531
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {v1, v0}, Ljava/nio/ByteBuffer;->position(I)Ljava/nio/Buffer;

    .line 533
    invoke-static {v10, v0}, Landroid/opengl/GLES11Ext;->glBindFramebufferOES(II)V

    .line 534
    invoke-static {v10, v0}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 536
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mResBuffer:Ljava/nio/ByteBuffer;

    invoke-virtual {p1, v0}, Landroid/graphics/Bitmap;->copyPixelsFromBuffer(Ljava/nio/Buffer;)V

    .line 538
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mTempCanvas:Landroid/graphics/Canvas;

    invoke-virtual {v0, p1}, Landroid/graphics/Canvas;->setBitmap(Landroid/graphics/Bitmap;)V

    .line 539
    invoke-direct {p0, p1}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->addSignatureInfo(Landroid/graphics/Bitmap;)V

    .line 540
    return-void

    .line 478
    .end local v7    # "iter":Ljava/util/ListIterator;, "Ljava/util/ListIterator<Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;>;"
    .end local v8    # "layerNumber":I
    .end local v9    # "lyersCount":I
    :cond_1
    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    goto :goto_0

    .line 481
    :cond_2
    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    goto :goto_1

    .line 498
    .restart local v7    # "iter":Ljava/util/ListIterator;, "Ljava/util/ListIterator<Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;>;"
    .restart local v8    # "layerNumber":I
    .restart local v9    # "lyersCount":I
    :cond_3
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mFBO:[I

    iget v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    aget v1, v1, v4

    invoke-static {v10, v1}, Landroid/opengl/GLES20;->glBindFramebuffer(II)V

    .line 499
    invoke-interface {v7}, Ljava/util/ListIterator;->next()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;

    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-interface {v1, v4}, Lcom/sonymobile/generativeartwork/layers/GenerativeLayer;->draw(Ljava/lang/Object;)V

    .line 500
    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOffscreenTexture:[I

    iget v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    aget v1, v1, v4

    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentTexture:I

    .line 503
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    add-int/lit8 v1, v1, 0x1

    rem-int/lit8 v1, v1, 0x2

    iput v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mCurrentFB:I

    .line 490
    add-int/lit8 v8, v8, 0x1

    goto :goto_2

    .line 509
    :cond_4
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    if-ge v1, v3, :cond_0

    goto :goto_3

    .line 516
    :cond_5
    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mOESFBO:I

    invoke-static {v10, v1}, Landroid/opengl/GLES11Ext;->glBindFramebufferOES(II)V

    const v1, 0x84c0

    .line 520
    invoke-static {v1}, Landroid/opengl/GLES20;->glActiveTexture(I)V

    goto :goto_4
.end method

.method public restoreContextIfNeeded()V
    .locals 6

    .prologue
    const/4 v5, 0x0

    .line 296
    iget-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    if-nez v0, :cond_0

    .line 306
    :goto_0
    return-void

    .line 297
    :cond_0
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    iget-object v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceDraw:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalSurfaceRead:Ljavax/microedition/khronos/egl/EGLSurface;

    iget-object v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalContext:Ljavax/microedition/khronos/egl/EGLContext;

    invoke-interface {v0, v1, v2, v3, v4}, Ljavax/microedition/khronos/egl/EGL10;->eglMakeCurrent(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLSurface;Ljavax/microedition/khronos/egl/EGLContext;)Z

    move-result v0

    if-nez v0, :cond_1

    .line 301
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->TAG:Ljava/lang/String;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string/jumbo v2, " disp: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEglOriginalDisplay:Ljavax/microedition/khronos/egl/EGLDisplay;

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string/jumbo v2, " Can\'t restore original context, err: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mEgl:Ljavax/microedition/khronos/egl/EGL10;

    invoke-interface {v2}, Ljavax/microedition/khronos/egl/EGL10;->eglGetError()I

    move-result v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string/jumbo v2, " maybe was no context bound before."

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Landroid/util/Log;->e(Ljava/lang/String;Ljava/lang/String;)I

    goto :goto_0

    .line 299
    :cond_1
    iput-boolean v5, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mNeedContextSwitch:Z

    goto :goto_0
.end method

.method public setupGlobalTransform(IILcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;)V
    .locals 9
    .param p1, "bmpWidth"    # I
    .param p2, "bmpHeight"    # I
    .param p3, "mode"    # Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;

    .prologue
    const/16 v8, 0xc11

    const/high16 v7, -0x40800000    # -1.0f

    const/high16 v6, 0x3f800000    # 1.0f

    const/high16 v5, 0x40000000    # 2.0f

    const/4 v4, 0x0

    .line 547
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-static {v0, v4}, Landroid/opengl/Matrix;->setIdentityM([FI)V

    .line 549
    sget-object v0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$1;->$SwitchMap$com$sonymobile$generativeartwork$render$OffscreenRenderer$Mode:[I

    invoke-virtual {p3}, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer$Mode;->ordinal()I

    move-result v1

    aget v0, v0, v1

    packed-switch v0, :pswitch_data_0

    .line 575
    :cond_0
    :goto_0
    return-void

    .line 552
    :pswitch_0
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    iget v1, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    sub-int v1, p1, v1

    int-to-float v1, v1

    div-float/2addr v1, v5

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    int-to-float v2, v2

    div-float/2addr v1, v2

    mul-float/2addr v1, v5

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    sub-int v2, p2, v2

    int-to-float v2, v2

    div-float/2addr v2, v5

    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    int-to-float v3, v3

    div-float/2addr v2, v3

    mul-float/2addr v2, v5

    const/4 v3, 0x0

    invoke-static {v0, v4, v1, v2, v3}, Landroid/opengl/Matrix;->translateM([FIFFF)V

    .line 556
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    int-to-float v1, p1

    iget v2, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    int-to-float v2, v2

    div-float/2addr v1, v2

    int-to-float v2, p2

    iget v3, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    int-to-float v3, v3

    div-float/2addr v2, v3

    mul-float/2addr v2, v7

    invoke-static {v0, v4, v1, v2, v6}, Landroid/opengl/Matrix;->scaleM([FIFFF)V

    .line 560
    iget-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    if-eqz v0, :cond_0

    .line 561
    invoke-static {v8}, Landroid/opengl/GLES20;->glDisable(I)V

    .line 562
    iput-boolean v4, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    goto :goto_0

    .line 567
    :pswitch_1
    iget-object v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mGlobalTransform:[F

    invoke-static {v0, v4, v6, v7, v6}, Landroid/opengl/Matrix;->scaleM([FIFFF)V

    .line 568
    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mWidth:I

    if-gt p1, v0, :cond_0

    iget v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mHeight:I

    if-gt p2, v0, :cond_0

    .line 569
    invoke-static {v4, v4, p1, p2}, Landroid/opengl/GLES20;->glScissor(IIII)V

    .line 570
    invoke-static {v8}, Landroid/opengl/GLES20;->glEnable(I)V

    .line 571
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/sonymobile/generativeartwork/render/OffscreenRenderer;->mScissorsEnabled:Z

    goto :goto_0

    .line 549
    nop

    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_0
        :pswitch_1
    .end packed-switch
.end method
